# Generated by Django 5.1.2 on 2024-10-18 20:43

from django.db import migrations

def create_predefined_organizations(apps, schema_editor):
    Organization = apps.get_model('supply_chain', 'Organization')
    org_types = ['FARM', 'PROCESSING', 'DISTRIBUTION', 'RETAILER']
    
    for org_type in org_types:
        for i in range(1, 6):
            Organization.objects.create(name=f"{org_type.capitalize()} {i}", org_type=org_type)

class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),  # Update this to match your actual initial migration
    ]

    operations = [
        migrations.RunPython(create_predefined_organizations),
    ]
