# Generated by Django 5.1.2 on 2024-10-18 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_create_predefined_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, help_text='Quantity in Kg'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Created', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
