# Generated by Django 5.1.2 on 2024-10-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_organization_org_hash_product_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_org_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_org_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
