# Generated by Django 5.1.2 on 2024-10-19 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0004_transaction_from_org_hash_transaction_to_org_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
