# Generated by Django 5.1.2 on 2024-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0005_alter_product_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='certificate',
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_ipfs_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
