# Generated by Django 5.1.2 on 2024-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0006_remove_product_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
