# Generated by Django 5.1.2 on 2024-10-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0007_product_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('FARM', 'Farm'), ('PROCESSING', 'Processing Unit'), ('DISTRIBUTION', 'Distribution Unit'), ('RETAIL', 'Retailer')], max_length=20),
        ),
    ]
