# Generated by Django 5.1.2 on 2024-10-19 21:45

import supply_chain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0008_alter_organization_org_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=supply_chain.models.get_ist_time),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=supply_chain.models.get_ist_time),
        ),
    ]
